# Color settings (Hex value without #)
color_alpha: e0e0e0
color_beta: cc2828

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Instagram API
instagram_key:
instagram_caption: true

# SEO settings
title: CHARLIE ROCKET photography
description:
url: "https://charlesrocket.github.io/photography"
email:
twitter_username: charlesrocket
default_img:

# Profile settings
social:
  twitter: https://twitter.com/charlesrocket

# Build settings
exclude: ["node_modules", "gulpfile.js", "assets/js/app.js", "README.md", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: none

# Sass
sass:
  style: compressed

plugins:
  - jekyll-gist
  - jekyll-sitemap
  - jekyll-mentions

exiftag:
 sources:
   - assets/images/portfolio

mini_magick:
    photography:
        source: assets/images/portfolio
        destination: assets/images/portfolio/thumbnails
        resize: "1280x720"
    headers:
        source: assets/images/headers
        destination: assets/images/headers/thumbnails
        resize: "400x250"
