---
title: CHARLIE ROCKET photography
color_alpha: e0e0e0
color_beta: cc2828
google_analytics: UA—XXXXXXXX-X
instagram_key:
instagram_caption: true
description:
url: https://charlesrocket.github.io/photography/
email:
twitter_username: charlesrocket
default_img:
social:
  twitter: https://twitter.com/charlesrocket
exclude:
- node_modules
- gulpfile.js
- assets/js/app.js
- Gemfile
- Gemfile.lock
- _javascript/vendor
markdown: kramdown
permalink: none
sass:
  style: compressed
plugins:
- jekyll-gist
- jekyll-sitemap
- jekyll-mentions
